### ISSUE TITLE
when open this plugin in android sutdio, it throws a error                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  n'n'n

### ISSUE THREAD

**Issue by RommiPlus** [obiscr/ChatGPT#19]
The detail error information as follows:

`Cannot init toolwindow com.obiscr.chatgpt.MyToolWindowFactory@54b67455

java.lang.NoClassDefFoundError: Could not initialize class org.intellij.plugins.markdown.ui.preview.jcef.MarkdownJCEFHtmlPanel
	at com.obiscr.chatgpt.ui.MainPanel.<init>(MainPanel.java:37)
	at com.obiscr.chatgpt.MyToolWindow.getContent(MyToolWindow.java:18)
	at com.obiscr.chatgpt.MyToolWindowFactory.createToolWindowContent(MyToolWindowFactory.java:31)
	at com.intellij.openapi.wm.impl.ToolWindowImpl.createContentIfNeeded$intellij_platform_ide_impl(ToolWindowImpl.kt:542)
	at com.intellij.openapi.wm.impl.ToolWindowImpl.scheduleContentInitializationIfNeeded$intellij_platform_ide_impl(ToolWindowImpl.kt:521)
	at com.intellij.openapi.wm.impl.ToolWindowManagerImpl.doShowWindow(ToolWindowManagerImpl.kt:1036)
	at com.intellij.openapi.wm.impl.ToolWindowManagerImpl.showToolWindowImpl(ToolWindowManagerImpl.kt:982)
	at com.intellij.openapi.wm.impl.ToolWindowManagerImpl.showToolWindowImpl$default(ToolWindowManagerImpl.kt:971)
	at com.intellij.openapi.wm.impl.ToolWindowManagerImpl.doRegisterToolWindow(ToolWindowManagerImpl.kt:1113)
	at com.intellij.openapi.wm.impl.ToolWindowManagerImpl.initToolWindows(ToolWindowManagerImpl.kt:535)
	at com.intellij.openapi.wm.impl.ToolWindowManagerImpl.access$initToolWindows(ToolWindowManagerImpl.kt:86)
	at com.intellij.openapi.wm.impl.ToolWindowManagerImpl$beforeProjectOpenedTask$1.run(ToolWindowManagerImpl.kt:451)
	at com.intellij.openapi.application.TransactionGuardImpl.runWithWritingAllowed(TransactionGuardImpl.java:214)
	at com.intellij.openapi.application.TransactionGuardImpl.access$200(TransactionGuardImpl.java:21)
	at com.intellij.openapi.application.TransactionGuardImpl$2.run(TransactionGuardImpl.java:196)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:805)
	at com.intellij.openapi.application.impl.ApplicationImpl.lambda$invokeLater$4(ApplicationImpl.java:348)
	at com.intellij.openapi.application.impl.FlushQueue.doRun(FlushQueue.java:82)
	at com.intellij.openapi.application.impl.FlushQueue.runNextEvent(FlushQueue.java:131)
	at com.intellij.openapi.application.impl.FlushQueue.flushNow(FlushQueue.java:47)
	at com.intellij.openapi.application.impl.FlushQueue$FlushNow.run(FlushQueue.java:187)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:313)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:776)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:727)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:746)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:891)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:760)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$6(IdeEventQueue.java:447)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:818)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$7(IdeEventQueue.java:446)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:805)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:492)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)`

android studio version inforamtion:

Android Studio Dolphin | 2021.3.1 Patch 1
Build #AI-213.7172.25.2113.9123335, built on September 30, 2022
Runtime version: 11.0.13+0-b1751.21-8125866 aarch64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 12.6
GC: G1 Young Generation, G1 Old Generation
Memory: 2048M
Cores: 8
Registry:
    external.system.auto.import.disabled=true
    ide.text.editor.with.preview.show.floating.toolbar=false

Non-Bundled Plugins:
    Dart (213.7433)
    io.flutter (71.0.3)
    SequenceDiagram (2.2.6)
    ChatGPT (1.0.1)

please look at this error, and find out how fix it, thank you.

**Comment by obiscr** [comment]
Thanks for report, I will take it.

**Comment by piereligio** [comment]
Sadly I can confirm it, also on 1.0.5 version. I'm on Android Studio Electric Eel | 2022.1.1 RC 1
Build #AI-221.6008.13.2211.9301383, built on November 17, 2022

**Comment by obiscr** [comment]
Thanks for the feedback. Please follow this [thread](https://jetbrains-platform.slack.com/archives/C5U8BM1MK/p1670916014619419)

**Comment by piereligio** [comment]
> Thanks for the feedback. This problem seems to be related to the version of AS. Please follow this [thread](https://jetbrains-platform.slack.com/archives/C5U8BM1MK/p1670916014619419)

Sadly I cannot join that, it says I'm not in the work area

**Comment by obiscr** [comment]
Ok, i'll follow up on this question.

**Comment by obiscr** [comment]
This is the latest progress on this issue：https://youtrack.jetbrains.com/issue/IDEA-308059/Can-not-launch-JCef-from-gradle-plugin-against-JDK-17-and-IDEA-2022.3

**Comment by obiscr** [comment]
对于中文：请参考 https://chatgpt.cn.obiscr.com/faq/ 的 `插件在Android Studio中无法使用？` 进行处理。
For english: Please see https://chatgpt.en.obiscr.com/faq/ `Plugins are not available in Android Studio?` to fix it.

Thank you all for report this issue. Enjoy!
