### ISSUE TITLE
怎么解决这个报错EasyCode token error: You cannot do this because you have created an account already

### ISSUE THREAD

**Issue by Meoooww** [obiscr/ChatGPT#253]
how to solve this problem?
![image](https://github.com/obiscr/ChatGPT/assets/56733007/92d260b4-9586-4c8e-970d-1717a0de63c9)
meanwhile i cant send anything in the textbox, the button is gray
同时，我无法点文本框的发送按钮
![image](https://github.com/obiscr/ChatGPT/assets/56733007/2eec1522-da11-4797-be78-119503eb6e11)

**Comment by obiscr** [comment]
Thanks, can you send the `idea.log` to my email: wuzi@obiscr.com

> meanwhile i cant send anything in the textbox, the button is gray

This is because the text box doesn't have any text in it, and once you enter text, the button will become available.

**Comment by Meoooww** [comment]
> Thanks, can you send the `idea.log` to my email: [wuzi@obiscr.com](mailto:wuzi@obiscr.com)
> 
> > meanwhile i cant send anything in the textbox, the button is gray
> 
> This is because the text box doesn't have any text in it, and once you enter text, the button will become available.

bt i cant click the button even when the textbox have text in it
meanwhile, how to solve the token error?
![image](https://github.com/obiscr/ChatGPT/assets/56733007/a97edc0a-7c31-4ec4-b6a5-a974f178f713)

**Comment by obiscr** [comment]
please send the idea.log to my email: [wuzi@obiscr.com](mailto:wuzi@obiscr.com)

**Comment by cjquery** [comment]
你好，我也遇到了这个问题，提示账户已创建一个账户。因为在内网使用文件无法外发，看日志是没有权限，这个看能帮忙屏蔽掉不，每次启动idea都会弹出很多错误提示：
2023-07-14 10:00:26,568 [ 121104]   INFO - #c.i.w.i.i.j.s.DelayedProjectSynchronizer - Workspace model loaded from cache. Syncing real project state into workspace model in 92 ms. Thread[ApplicationImpl pooled thread 2,4,main]
2023-07-14 10:00:36,422 [ 130958] SEVERE - a.e.a.EasyCodeManager - EasyCode Manager check token failed, cause: Permission denied: no further information
2023-07-14 10:00:36,446 [ 130982] SEVERE - a.e.a.EasyCodeManager - EasyCode Manager refresh token failed, cause: Permission denied: no further information
2023-07-14 10:00:36,446 [ 130982] SEVERE - c.o.c.c.SendAction - ChatGPT - EasyCode: send message check & get token failed.
2023-07-14 10:00:36,493 [ 131029]   INFO - c.o.c.EasyCodeHandler - ChatGPT - EasyCode: conversation failure. Response=null, errorMessage=Permission denied: no further information
2023-07-14 10:00:36,494 [ 131030]   INFO - STDERR - java.net.SocketException: Permission denied: no further information
2023-07-14 10:00:36,494 [ 131030]   INFO - STDERR - 	at java.base/sun.nio.ch.Net.pollConnect(Native Method)
2023-07-14 10:00:36,494 [ 131030]   INFO - STDERR - 	at java.base/sun.nio.ch.Net.pollConnectNow(Net.java:672)
2023-07-14 10:00:36,494 [ 131030]   INFO - STDERR - 	at java.base/sun.nio.ch.NioSocketImpl.timedFinishConnect(NioSocketImpl.java:549)
2023-07-14 10:00:36,494 [ 131030]   INFO - STDERR - 	at java.base/sun.nio.ch.NioSocketImpl.connect(NioSocketImpl.java:597)
2023-07-14 10:00:36,494 [ 131030]   INFO - STDERR - 	at java.base/java.net.SocksSocketImpl.connect(SocksSocketImpl.java:327)
2023-07-14 10:00:36,494 [ 131030]   INFO - STDERR - 	at java.base/java.net.Socket.connect(Socket.java:633)
2023-07-14 10:00:36,495 [ 131031]   INFO - STDERR - 	at okhttp3.internal.platform.Platform.connectSocket(Platform.kt:128)
2023-07-14 10:00:36,495 [ 131031]   INFO - STDERR - 	at okhttp3.internal.connection.RealConnection.connectSocket(RealConnection.kt:295)
2023-07-14 10:00:36,495 [ 131031]   INFO - STDERR - 	at okhttp3.internal.connection.RealConnection.connect(RealConnection.kt:207)
2023-07-14 10:00:36,495 [ 131031]   INFO - STDERR - 	at okhttp3.internal.connection.ExchangeFinder.findConnection(ExchangeFinder.kt:226)
2023-07-14 10:00:36,495 [ 131031]   INFO - STDERR - 	at okhttp3.internal.connection.ExchangeFinder.findHealthyConnection(ExchangeFinder.kt:106)
2023-07-14 10:00:36,495 [ 131031]   INFO - STDERR - 	at okhttp3.internal.connection.ExchangeFinder.find(ExchangeFinder.kt:74)
2023-07-14 10:00:36,495 [ 131031]   INFO - STDERR - 	at okhttp3.internal.connection.RealCall.initExchange$okhttp(RealCall.kt:255)
2023-07-14 10:00:36,495 [ 131031]   INFO - STDERR - 	at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.kt:32)
2023-07-14 10:00:36,495 [ 131031]   INFO - STDERR - 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
2023-07-14 10:00:36,495 [ 131031]   INFO - STDERR - 	at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.kt:95)
2023-07-14 10:00:36,495 [ 131031]   INFO - STDERR - 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
2023-07-14 10:00:36,495 [ 131031]   INFO - STDERR - 	at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.kt:83)
2023-07-14 10:00:36,495 [ 131031]   INFO - STDERR - 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
2023-07-14 10:00:36,495 [ 131031]   INFO - STDERR - 	at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.kt:76)
2023-07-14 10:00:36,496 [ 131032]   INFO - STDERR - 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
2023-07-14 10:00:36,496 [ 131032]   INFO - STDERR - 	at okhttp3.internal.connection.RealCall.getResponseWithInterceptorChain$okhttp(RealCall.kt:201)
2023-07-14 10:00:36,496 [ 131032]   INFO - STDERR - 	at okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:517)
2023-07-14 10:00:36,496 [ 131032]   INFO - STDERR - 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
2023-07-14 10:00:36,496 [ 131032]   INFO - STDERR - 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
2023-07-14 10:00:36,496 [ 131032]   INFO - STDERR - 	at java.base/java.lang.Thread.run(Thread.java:833)
2023-07-14 10:00:36,542 [ 131078] SEVERE - c.o.c.u.MixpanelUtil - ChatGPT - EasyCode: sendEvent exception, cause: Permission denied: no further information

**Comment by obiscr** [comment]
抱歉修改了你的一些提交信息。
对，您这边也是网络问题导致，目前这个提示暂时无法直接屏蔽，不过这个可以在后期优化，麻烦新创建一个优化提示的issue，这个issue会被关闭掉。

**Comment by obiscr** [comment]
@Meoooww Hello, according to the logs, this is a problem with your network and you can't access the server, so EasyCode Tab is not working. Please check if the proxy is turned on, if so, try turning it off. Restart the IDE to see if it works.
If it still doesn't work, then don't use EasyCode Tab yet, you can use other tabs instead.
