### ISSUE TITLE
Couldn't quite get it to run on IntelliJ

### ISSUE THREAD

**Issue by Bnjorogedev** [obiscr/ChatGPT#27]
hey. I tried installing the plugin on IntelliJ but could't get it working for some reason. I am using IntelliJ. Build #IU-222.4459.24, on MacOS. I have copied my Access Token(with and without the "") to the TextBox per the Instructions but could't get a prompt sent. Is there something I might be missing in the processs? Please let me know.

**Comment by obiscr** [comment]
Hi，please download the [latest version](https://plugins.jetbrains.com/files/20603/264795/ChatGPT-1.0.5.zip), and see [Getting Started](https://docs.obiscr.com/article/GPT-Getting-Started) or [Q&A](https://docs.obiscr.com/article/GPT-Getting-Started).

It's shoule be fix.

**Comment by Bnjorogedev** [comment]
Hi, thanks for responding! Is that an executable?

**Comment by Bnjorogedev** [comment]
Got it working thanks! but I still get a No Class Error Found. StackTrace below:
java.lang.NoClassDefFoundError: com/alibaba/fastjson2/JSONObject
	at com.obiscr.chatgpt.core.builder.OfficialBuilder.build(OfficialBuilder.java:15)
	at com.obiscr.chatgpt.ui.listener.SendListener.doActionPerformed(SendListener.java:80)
	at com.obiscr.chatgpt.ui.listener.SendListener.actionPerformed(SendListener.java:41)
	at java.desktop/javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:1972)
	at java.desktop/javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2313)
	at java.desktop/javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:405)
	at java.desktop/javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:262)
	at java.desktop/javax.swing.AbstractButton.doClick(AbstractButton.java:374)
	at java.desktop/javax.swing.AbstractButton.doClick(AbstractButton.java:354)
	at com.obiscr.chatgpt.ui.listener.SendListener.keyPressed(SendListener.java:137)
	at java.desktop/java.awt.Component.processKeyEvent(Component.java:6606)
	at java.desktop/javax.swing.JComponent.processKeyEvent(JComponent.java:2899)
	at java.desktop/java.awt.Component.processEvent(Component.java:6425)
	at java.desktop/java.awt.Container.processEvent(Container.java:2266)
	at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:5022)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2324)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4854)
	at java.desktop/java.awt.KeyboardFocusManager.redispatchEvent(KeyboardFocusManager.java:1964)
	at java.desktop/java.awt.DefaultKeyboardFocusManager.dispatchKeyEvent(DefaultKeyboardFocusManager.java:886)
	at java.desktop/java.awt.DefaultKeyboardFocusManager.preDispatchKeyEvent(DefaultKeyboardFocusManager.java:1166)
	at java.desktop/java.awt.DefaultKeyboardFocusManager.typeAheadAssertions(DefaultKeyboardFocusManager.java:1023)
	at java.desktop/java.awt.DefaultKeyboardFocusManager.dispatchEvent(DefaultKeyboardFocusManager.java:849)
	at com.intellij.ide.IdeKeyboardFocusManager.lambda$dispatchEvent$0(IdeKeyboardFocusManager.java:48)
	at com.intellij.openapi.application.TransactionGuardImpl.performActivity(TransactionGuardImpl.java:105)
	at com.intellij.ide.IdeEventQueue.performActivity(IdeEventQueue.java:624)
	at com.intellij.ide.IdeKeyboardFocusManager.dispatchEvent(IdeKeyboardFocusManager.java:48)
	at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:4903)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2324)
	at java.desktop/java.awt.Window.dispatchEventImpl(Window.java:2802)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4854)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:781)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:730)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:724)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:97)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:754)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:752)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:751)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:918)
	at com.intellij.ide.IdeEventQueue.dispatchKeyEvent(IdeEventQueue.java:827)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:760)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$6(IdeEventQueue.java:450)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:791)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$7(IdeEventQueue.java:449)
	at com.intellij.openapi.application.TransactionGuardImpl.performActivity(TransactionGuardImpl.java:113)
	at com.intellij.ide.IdeEventQueue.performActivity(IdeEventQueue.java:624)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$8(IdeEventQueue.java:447)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:881)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:493)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:207)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:128)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:117)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:105)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:92)
Caused by: java.lang.ClassNotFoundException: com.alibaba.fastjson2.JSONObject PluginClassLoader(plugin=PluginDescriptor(name=ChatGPT, id=ChatGPT, descriptorPath=plugin.xml, path=~/Library/Application Support/JetBrains/IntelliJIdea2022.2/plugins/ChatGPT-1.0.5.jar, version=1.0.5, package=null, isBundled=false), packagePrefix=null, instanceId=293, state=active)
	... 58 more

**Comment by obiscr** [comment]
Try this way:
Step 1: Uninstall the plugin and restart the IDE.
Step 2: Reinstall the plugin and restart the IDE.

**Comment by Bnjorogedev** [comment]
Hmm, thanks for responding. No luck when trying to do that though. I'm on version 1.05 of the extension installed it manually.

**Comment by obiscr** [comment]
Ok, But before installtation, please uninstall at first.

**Comment by Bnjorogedev** [comment]
No luck after trying to uninstall and reinstall. Any other ideas?

**Comment by obiscr** [comment]
Can you record a gif picture. Or provide some screenshots. let me have a look.

**Comment by Bnjorogedev** [comment]
It's the same exact problem described in the other issues. 
<img width="466" alt="image" src="https://user-images.githubusercontent.com/46893322/207253708-9cc9a684-6965-4f54-81e0-6883ebfe6568.png">
Here's the image

**Comment by Bnjorogedev** [comment]
I updated the extension but get this error now

**Comment by obiscr** [comment]
This is because of a problem with OpenAI's server.
You can find more info at :
https://github.com/mpociot/chatgpt-vscode/issues/15#issuecomment-1347878188
https://github.com/transitive-bullshit/chatgpt-api/issues/96#issuecomment-1347717784
https://github.com/acheong08/ChatGPT/issues/261#issuecomment-1347816761

**Comment by Bnjorogedev** [comment]
Thanks for the new update. Seems like Google disabled the ability for Third Parties to use Google Sign ins

**Comment by obiscr** [comment]
You are welcome.
