### ISSUE TITLE
一直响应失败

### ISSUE THREAD

**Issue by wzAtbj** [obiscr/ChatGPT#299]
写一句关于春天的诗
Response failure, please try again. Error message: { "error": { "message": "You exceeded your current quota, please check your plan and billing details.", "type": "insufficient_quota", "param": null, "code": "insufficient_quota" } }

配置是3.5-turbo

**Comment by obiscr** [comment]
您好，这个看起来是你当前账号的token已经使用完了，请更换一个新的账号，它应该可以工作。

**Comment by wzAtbj** [comment]
有个报错，还经常出现  

Translation error: 'java.io.OutputStream com.intellij.util.io.PathKt.outputStream$default(java.nio.file.Path, boolean, int, java.lang.Object)'
  
  java.lang.NoSuchMethodError: 'java.io.OutputStream com.intellij.util.io.PathKt.outputStream$default(java.nio.file.Path, boolean, int, java.lang.Object)'
at cn.yiiguxing.plugin.translate.util.IOKt.writeSafe(IO.kt:24)
at cn.yiiguxing.plugin.translate.service.CacheService.putDiskCache(CacheService.kt:63)
at cn.yiiguxing.plugin.translate.trans.TranslateClient.execute(TranslateClient.kt:59)
at cn.yiiguxing.plugin.translate.trans.google.GoogleTranslator.translateDocumentation(GoogleTranslator.kt:112)
at cn.yiiguxing.plugin.translate.trans.google.GoogleTranslator.translateDocumentation(GoogleTranslator.kt:75)
at cn.yiiguxing.plugin.translate.documentation.HtmlTranslatorKt.getTranslatedDocumentation(HtmlTranslator.kt:104)
at cn.yiiguxing.plugin.translate.documentation.HtmlTranslatorKt.getTranslatedDocumentation(HtmlTranslator.kt:38)
at cn.yiiguxing.plugin.translate.documentation.TranslateDocumentationTask$special$$inlined$runAsync$1.run(promise.kt:402)
at com.intellij.util.concurrency.ContextRunnable.run(ContextRunnable.java:24)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:702)
at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:699)
at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:699)
at java.base/java.lang.Thread.run(Thread.java:833)

**Comment by wzAtbj** [comment]
显示为翻译插件的问题
![image](https://github.com/obiscr/ChatGPT/assets/40134547/58722fb6-afb5-47f0-9942-501274777bd3)
