### ISSUE TITLE
wasn't able to open a panel

### ISSUE THREAD

**Issue by halradaideh** [obiscr/ChatGPT#40]
I got ths

```
java.lang.NullPointerException: Cannot invoke "com.obiscr.chatgpt.ui.MainPanel.getSearchTextArea()" because the return value of "com.obiscr.chatgpt.core.DataFactory.getMainPanel()" is null
	at com.obiscr.chatgpt.core.SendAction.doActionPerformed(SendAction.java:38)
	at com.obiscr.chatgpt.ui.action.editor.AbstractEditorAction.actionPerformed(AbstractEditorAction.java:33)
	at com.obiscr.chatgpt.ui.action.editor.OptimizeAction.actionPerformed(OptimizeAction.java:22)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.doPerformActionOrShowPopup(ActionUtil.java:323)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.lambda$performActionDumbAwareWithCallbacks$4(ActionUtil.java:302)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.performDumbAwareWithCallbacks(ActionUtil.java:346)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.performActionDumbAwareWithCallbacks(ActionUtil.java:302)
	at com.intellij.openapi.actionSystem.impl.ActionMenuItem.lambda$performAction$5(ActionMenuItem.java:296)
	at com.intellij.openapi.wm.impl.FocusManagerImpl.runOnOwnContext(FocusManagerImpl.java:226)
	at com.intellij.openapi.actionSystem.impl.ActionMenuItem.performAction(ActionMenuItem.java:289)
	at com.intellij.openapi.actionSystem.impl.ActionMenuItem.lambda$new$0(ActionMenuItem.java:64)
	at java.desktop/javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:1972)
	at com.intellij.openapi.actionSystem.impl.ActionMenuItem.lambda$fireActionPerformed$4(ActionMenuItem.java:111)
	at com.intellij.openapi.application.TransactionGuardImpl.performActivity(TransactionGuardImpl.java:105)
	at com.intellij.openapi.application.TransactionGuardImpl.performUserActivity(TransactionGuardImpl.java:94)
	at com.intellij.openapi.actionSystem.impl.ActionMenuItem.fireActionPerformed(ActionMenuItem.java:111)
	at com.intellij.ui.plaf.beg.BegMenuItemUI.doClick(BegMenuItemUI.java:526)
	at com.intellij.ui.plaf.beg.BegMenuItemUI$MyMouseInputHandler.mouseReleased(BegMenuItemUI.java:558)
	at java.desktop/java.awt.Component.processMouseEvent(Component.java:6648)
	at java.desktop/javax.swing.JComponent.processMouseEvent(JComponent.java:3392)
	at java.desktop/java.awt.Component.processEvent(Component.java:6413)
	at java.desktop/java.awt.Container.processEvent(Container.java:2266)
	at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:5022)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2324)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4854)
	at java.desktop/java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4948)
	at java.desktop/java.awt.LightweightDispatcher.processMouseEvent(Container.java:4575)
	at java.desktop/java.awt.LightweightDispatcher.dispatchEvent(Container.java:4516)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2310)
	at java.desktop/java.awt.Window.dispatchEventImpl(Window.java:2802)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4854)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:781)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:730)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:724)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:97)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:754)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:752)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:751)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:909)
	at com.intellij.ide.IdeEventQueue.dispatchMouseEvent(IdeEventQueue.java:831)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:753)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$5(IdeEventQueue.java:437)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:772)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$6(IdeEventQueue.java:436)
	at com.intellij.openapi.application.TransactionGuardImpl.performActivity(TransactionGuardImpl.java:113)
	at com.intellij.ide.IdeEventQueue.performActivity(IdeEventQueue.java:615)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$7(IdeEventQueue.java:434)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:813)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:480)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:207)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:128)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:117)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:105)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:92)
```

**Comment by miroslaws8** [comment]
The same problem

**Comment by obiscr** [comment]
Thanks for report. Please provide more information. Such as:

```
What your ide? (eg IDEA / PyCharm / GoLand...)
IDE Version? (eg 2022.2.1)
Plugin Version? (eg 2.0.0)
```

You can also provide `idea.log` with me. Thanks!

**Comment by miroslaws8** [comment]
What your ide? PhpStorm
IDE Version? 2022.2.3
Plugin Version? 2.0.0-222.223

I noticed that com.obiscr.chatgpt.core.DataFactory is missing the getMainPanel method even though it is being called.

**Comment by obiscr** [comment]
> What your ide? PhpStorm IDE Version? 2022.2.3 Plugin Version? 2.0.0-222.223
> 
> I noticed that com.obiscr.chatgpt.core.DataFactory is missing the getMainPanel method even though it is being called.

Got it, thanks.

**Comment by obiscr** [comment]
> What your ide? PhpStorm IDE Version? 2022.2.3 Plugin Version? 2.0.0-222.223
> 
> I noticed that com.obiscr.chatgpt.core.DataFactory is missing the getMainPanel method even though it is being called.

![image](https://user-images.githubusercontent.com/28687074/214468446-9d5c28eb-f34e-4dbe-b4d4-f59296e8dd73.png)

In my tests, it works fine.

Can you tell me what action you used to trigger this problem, and can you provide a video. Start by opening PhpStorm. Thanks！

**Comment by miroslaws8** [comment]
I think I understand the reason for this error, I do not have the ChatGPT panel on the right as you do.

**Comment by obiscr** [comment]
Ok, because I use it normally here, there is no way to test it. So you still have a problem, please provide the video or gif you used to help me better locate the problem.

**Comment by obiscr** [comment]
> I think I understand the reason for this error, I do not have the ChatGPT panel on the right as you do.

Ok, because I use it normally here, there is no way to test it. So if you still have problems, please provide the video or gif you used to help me better locate the problem.

**Comment by mrSerg** [comment]
Have the same problem
<img width="423" alt="image" src="https://user-images.githubusercontent.com/5166808/215039129-3ed46efe-08d0-4823-869b-68b68b3d492c.png">
macOS 13.2 (22D49)

**Comment by mrSerg** [comment]
Found how to solve in new versions of PHPStorm
Need to open it first there
<img width="368" alt="image" src="https://user-images.githubusercontent.com/5166808/215042602-24c68277-7b90-4094-9797-c21324aca498.png">

**Comment by obiscr** [comment]
Please try the following steps:
1. First open or create a new project (**note that it must be a project, not a separate file**).

Then use the ChatGPT plug-in and it should work normally.
